//! Server-side highlight offset calculation.
//!
//! LanceDB / Lance BM25 does not expose per-hit term offsets via its
//! public API (only `_score` is returned). To still surface visually
//! correct highlight ranges in the UI, this module re-tokenizes the
//! hit's content with the **same tokenizer settings** that drive the
//! BM25 inverted index, finds tokens that match the user's query, and
//! reports those tokens' byte / UTF-16 offsets to the client.
//!
//! Returning **both** UTF-8 byte offsets and UTF-16 code-unit offsets
//! is intentional: Rust slices are byte-indexed (`&str`), JS
//! `String.prototype.slice` is UTF-16 code-unit-indexed. Computing
//! both server-side avoids a per-render `byte → code-unit` conversion
//! in the browser and prevents the well-known "find the same word
//! twice and always highlight the first occurrence" bug that a
//! client-side `String.indexOf()` fallback exhibits.

use std::borrow::Cow;
use std::collections::HashSet;
use std::sync::OnceLock;

use rust_stemmers::{Algorithm, Stemmer};

use protobuf::llm_memory::data::{HighlightField, HighlightRange, HighlightSource};

use super::config::{FtsConfig, FtsTokenizerKind};

/// Compute highlight ranges for `text` against `query` using the FTS
/// tokenizer described by `fts`.
///
/// All offsets satisfy `text.is_char_boundary(byte_start)` and
/// `text.is_char_boundary(byte_start + byte_length)` — verified via
/// `debug_assert!` so test failures surface during development without
/// inflating release binaries. Reaching the lindera branch on a binary
/// built without the `lindera` feature is a programming error
/// (startup-time `FtsTokenizerKind::requires_lindera` already rejects
/// it), but the runtime path returns an empty vec instead of panicking
/// to keep the call site total.
pub fn compute_highlights(text: &str, query: &str, fts: &FtsConfig) -> Vec<HighlightRange> {
    if text.is_empty() || query.is_empty() {
        return Vec::new();
    }

    // Mirror the lance-native FTS filter chain (lance-index 4.0.0
    // `InvertedIndexParams::build`, tokenizer.rs:338-379):
    //   RemoveLongFilter → LowerCaser → Stemmer → StopWordFilter → AsciiFoldingFilter
    // applied in that order. Returning `None` means "drop this token"
    // (long token / stop word) so it never enters the comparison set.
    let normalize_for_match = |s: &str| -> Option<String> {
        // tantivy's `RemoveLongFilter` keeps tokens whose UTF-8 byte
        // length is **strictly less** than the limit
        // (`token.text.len() < limit`, see tantivy
        // `tokenizer/remove_long.rs:36`). Mirror that exactly: drop
        // when `s.len() >= limit`. Using char count or `> limit` would
        // misclassify multi-byte (CJK) tokens and the boundary case
        // `len == limit`, putting BM25 hits and highlight ranges out
        // of sync at exactly the points where the divergence matters.
        if let Some(limit) = fts.max_token_length
            && s.len() >= limit
        {
            return None;
        }
        let mut out = if fts.lower_case {
            s.to_lowercase()
        } else {
            s.to_string()
        };
        if fts.stem {
            out = apply_english_stem(&out);
        }
        if fts.remove_stop_words && is_english_stop_word(&out) {
            return None;
        }
        if fts.ascii_folding {
            out = ascii_fold(&out);
        }
        if out.is_empty() {
            return None;
        }
        Some(out)
    };

    // Hash-set lookup so the inner loop runs in O(1) per text token
    // instead of scanning the query token list. Empty / blank query
    // tokens are filtered out so a user query like "  " never matches
    // every space-prefixed token in the content.
    let query_set: HashSet<String> = tokenize_for_match(query, fts)
        .into_iter()
        .filter_map(|tok| normalize_for_match(&tok.text))
        .collect();
    if query_set.is_empty() {
        return Vec::new();
    }

    let text_tokens = tokenize_for_match(text, fts);
    if text_tokens.is_empty() {
        return Vec::new();
    }

    // Pre-compute a (byte_offset → utf16_offset) prefix map by walking
    // `text` exactly once. This makes the per-token utf16_start lookup
    // O(1) and guarantees that the same byte position always yields
    // the same utf16 index even when the token list itself was
    // generated by a different code path (lindera vs. ngram).
    let utf16_prefix = build_utf16_prefix_map(text);

    let mut ranges: Vec<HighlightRange> = Vec::new();
    for tok in &text_tokens {
        if tok.byte_end <= tok.byte_start || tok.byte_end > text.len() {
            continue;
        }
        let Some(normalized) = normalize_for_match(&tok.text) else {
            continue;
        };
        if !query_set.contains(&normalized) {
            continue;
        }
        debug_assert!(
            text.is_char_boundary(tok.byte_start),
            "byte_start {} is not on a char boundary",
            tok.byte_start
        );
        debug_assert!(
            text.is_char_boundary(tok.byte_end),
            "byte_end {} is not on a char boundary",
            tok.byte_end
        );

        let byte_start = tok.byte_start as u32;
        let byte_length = (tok.byte_end - tok.byte_start) as u32;
        let utf16_start = utf16_prefix[tok.byte_start];
        let utf16_end = utf16_prefix[tok.byte_end];
        let utf16_length = utf16_end - utf16_start;

        ranges.push(HighlightRange {
            byte_start,
            byte_length,
            utf16_start,
            utf16_length,
        });
    }
    merge_ranges(ranges, &utf16_prefix)
}

/// Collapse overlapping and adjacent (`a.end == b.start`) ranges into
/// single contiguous spans. The ngram tokenizer emits one window per
/// `n ∈ [min, max]` per starting char, so a query like `"rust"`
/// against `text="rust"` produces five overlapping fragments
/// (`ru`/`us`/`st`/`rus`/`ust`); without this pass the client would
/// render five layered `<mark>` tags instead of one. Multi-token
/// tokenizers (lindera, simple) also benefit when consecutive tokens
/// match — e.g. `"自然言語"` becomes a single span rather than two
/// touching ones.
///
/// The output is sorted by `byte_start` and pairwise non-overlapping;
/// `utf16_*` fields are recomputed from `utf16_prefix` so they stay
/// consistent with the merged byte range.
fn merge_ranges(mut ranges: Vec<HighlightRange>, utf16_prefix: &[u32]) -> Vec<HighlightRange> {
    if ranges.len() <= 1 {
        return ranges;
    }
    ranges.sort_by_key(|r| (r.byte_start, r.byte_length));

    let mut merged: Vec<HighlightRange> = Vec::with_capacity(ranges.len());
    for r in ranges {
        let r_end = r.byte_start + r.byte_length;
        match merged.last_mut() {
            // Adjacent (touching) or overlapping → extend the last span.
            Some(prev) if prev.byte_start + prev.byte_length >= r.byte_start => {
                let prev_end = prev.byte_start + prev.byte_length;
                if r_end > prev_end {
                    prev.byte_length = r_end - prev.byte_start;
                }
            }
            _ => merged.push(r),
        }
    }

    for r in &mut merged {
        let bs = r.byte_start as usize;
        let be = bs + r.byte_length as usize;
        // bs/be originate from token spans that already cleared the
        // char-boundary debug_asserts in compute_highlights, so the
        // utf16_prefix lookup below is well-defined.
        r.utf16_start = utf16_prefix[bs];
        let utf16_end = utf16_prefix[be];
        r.utf16_length = utf16_end - r.utf16_start;
    }
    merged
}

/// Compute highlights for a single search-result field and wrap them
/// in a `HighlightField` with the given `source`. Returns an empty
/// `Vec` (not `Option`) so callers can splat the result into the
/// proto message without an extra `unwrap_or_default`.
///
/// `text` is `Option<&str>` because the upstream proto fields
/// (`Memory.data.content`, `Thread.data.description`) come in as
/// optionals — passing `None` here is equivalent to passing an empty
/// string and short-circuits before the tokenizer runs.
pub fn compute_highlight_field(
    text: Option<&str>,
    query_and_cfg: Option<(&str, &FtsConfig)>,
    source: HighlightSource,
) -> Vec<HighlightField> {
    let Some((query, fts)) = query_and_cfg else {
        return Vec::new();
    };
    let Some(text) = text.filter(|t| !t.is_empty()) else {
        return Vec::new();
    };
    let ranges = compute_highlights(text, query, fts);
    if ranges.is_empty() {
        Vec::new()
    } else {
        vec![HighlightField {
            source: source as i32,
            ranges,
        }]
    }
}

/// A token discovered inside a piece of text. Mirrors what we need
/// from `lindera::token::Token` so the ngram / whitespace fallbacks
/// can keep working on builds without the `lindera` feature.
///
/// `text` is `Cow<'a, str>` so the in-process tokenizers can borrow
/// directly out of the source string while the lindera path still
/// keeps its owned values from `Token::text`.
pub(crate) struct TokenSpan<'a> {
    pub byte_start: usize,
    pub byte_end: usize,
    pub text: Cow<'a, str>,
}

/// Tokenize `text` using the same family of tokenizer the FTS index
/// runs. Always exposed (regardless of build features) so unit tests
/// can exercise the ngram / whitespace branches without needing a
/// Lindera dictionary on disk. The Lindera branch is gated to the
/// feature flag.
pub(crate) fn tokenize_for_match<'a>(text: &'a str, fts: &FtsConfig) -> Vec<TokenSpan<'a>> {
    match fts.tokenizer {
        FtsTokenizerKind::Whitespace => whitespace_tokens(text),
        FtsTokenizerKind::Simple => simple_tokens(text),
        FtsTokenizerKind::Raw => raw_token(text),
        FtsTokenizerKind::Ngram => {
            ngram_tokens(text, fts.ngram_min, fts.ngram_max, fts.ngram_prefix_only)
        }
        FtsTokenizerKind::LinderaIpadic
        | FtsTokenizerKind::LinderaUnidic
        | FtsTokenizerKind::LinderaKoDic => lindera_tokens(text, fts.tokenizer),
    }
}

/// Build a `byte_index → utf16_offset` table such that `map[i]`
/// equals `text[..i].encode_utf16().count()` **for every char
/// boundary `i`** (`0`, the start of every code point, and
/// `text.len()`). The map has length `text.len() + 1` so callers can
/// index the past-the-end position used by `byte_end`.
///
/// Indices that fall *inside* a multi-byte code point hold the same
/// value as the start of that code point, not an interpolated
/// "halfway" offset — they would not encode UTF-16 anyway, so the
/// value is meaningless. `compute_highlights` only looks up offsets
/// at boundaries (a `debug_assert!` enforces this), so the in-token
/// fill is safe to ignore.
fn build_utf16_prefix_map(text: &str) -> Vec<u32> {
    let mut map = vec![0u32; text.len() + 1];
    let mut acc: u32 = 0;
    for (idx, ch) in text.char_indices() {
        // every byte from `idx..idx+ch.len_utf8()` shares the running utf16 acc
        let end = idx + ch.len_utf8();
        for slot in &mut map[idx..end] {
            *slot = acc;
        }
        acc += ch.len_utf16() as u32;
    }
    map[text.len()] = acc;
    map
}

/// Whitespace-delimited tokens.
fn whitespace_tokens(text: &str) -> Vec<TokenSpan<'_>> {
    split_tokens_by(text, |ch| !ch.is_whitespace())
}

/// Tantivy's "simple" tokenizer splits on every non-alphanumeric
/// char. We mirror that here so a query like "rust" against
/// `text = "rust-lang"` highlights `rust` correctly.
fn simple_tokens(text: &str) -> Vec<TokenSpan<'_>> {
    split_tokens_by(text, char::is_alphanumeric)
}

/// Walk `text` once, gathering contiguous runs of characters for
/// which `is_token_char` returns true. Shared body for the
/// whitespace / simple tokenizers because they only differ in the
/// per-char predicate.
fn split_tokens_by(text: &str, is_token_char: impl Fn(char) -> bool) -> Vec<TokenSpan<'_>> {
    let mut out = Vec::new();
    let mut start: Option<usize> = None;
    for (idx, ch) in text.char_indices() {
        if is_token_char(ch) {
            if start.is_none() {
                start = Some(idx);
            }
        } else if let Some(s) = start {
            out.push(TokenSpan {
                byte_start: s,
                byte_end: idx,
                text: Cow::Borrowed(&text[s..idx]),
            });
            start = None;
        }
    }
    if let Some(s) = start {
        out.push(TokenSpan {
            byte_start: s,
            byte_end: text.len(),
            text: Cow::Borrowed(&text[s..]),
        });
    }
    out
}

/// `raw` mode treats the entire field as a single token — highlights
/// only fire when the query exactly matches the whole text.
fn raw_token(text: &str) -> Vec<TokenSpan<'_>> {
    vec![TokenSpan {
        byte_start: 0,
        byte_end: text.len(),
        text: Cow::Borrowed(text),
    }]
}

/// Character n-gram tokens of every length `n ∈ [min, max]`, sliding
/// by one character at a time. Mirrors LanceDB's ngram BM25 mode used
/// as the non-Lindera Japanese fallback.
///
/// When `prefix_only` is true, only emit n-grams that begin at byte
/// 0. This mirrors tantivy's `NgramTokenStream::advance`
/// (`tantivy/src/tokenizer/ngram_tokenizer.rs:163-177`) which
/// terminates the token stream as soon as `offset_from > 0`. Keeping
/// the highlight-side ngram set identical to the index-side set is
/// the whole point of this function — diverging here would produce
/// highlights for n-grams the BM25 index never indexed.
fn ngram_tokens(text: &str, min: u32, max: u32, prefix_only: bool) -> Vec<TokenSpan<'_>> {
    if min == 0 || min > max {
        return Vec::new();
    }
    let chars: Vec<(usize, char)> = text.char_indices().collect();
    if chars.is_empty() {
        return Vec::new();
    }
    let total_bytes = text.len();
    let mut out = Vec::new();
    for n in min..=max {
        let n_usize = n as usize;
        for window in chars.windows(n_usize) {
            let byte_start = window[0].0;
            // Prefix-only mode: tantivy's stream stops at the first
            // non-zero offset, so equivalently we only keep windows
            // anchored at byte 0.
            if prefix_only && byte_start != 0 {
                break;
            }
            let last = window[n_usize - 1];
            // Past-the-end byte offset of the final char in the
            // window — falls back to `total_bytes` for the trailing
            // window since `chars` does not store a sentinel.
            let byte_end = last.0 + last.1.len_utf8();
            debug_assert!(byte_end <= total_bytes);
            out.push(TokenSpan {
                byte_start,
                byte_end,
                text: Cow::Borrowed(&text[byte_start..byte_end]),
            });
        }
    }
    out
}

/// Lindera-backed tokenization. Tokenizer instances are cached in a
/// process-wide `OnceLock` keyed by `FtsTokenizerKind` so the heavy
/// dictionary load (~30 MB for IPADIC) happens at most once per
/// dictionary kind per process — without this cache, every search hit
/// re-loads the dictionary from disk and saturates CPU + filesystem
/// cache.
#[cfg(feature = "lindera")]
fn lindera_tokens(text: &str, kind: FtsTokenizerKind) -> Vec<TokenSpan<'static>> {
    use std::borrow::Cow;

    let tokenizer = match lindera_cache::get_or_init(kind) {
        Some(t) => t,
        None => {
            // Dictionary load already failed once for this kind and
            // was cached as `None`. Returning empty matches the
            // contract: highlights are best-effort and the absence of
            // a dictionary on disk should not poison the search RPC.
            return Vec::new();
        }
    };

    match tokenizer.tokenize(&Cow::Borrowed(text)) {
        Ok(tokens) => tokens
            .into_iter()
            .map(|t| TokenSpan {
                byte_start: t.byte_start,
                byte_end: t.byte_end,
                text: Cow::Owned(t.text.into_owned()),
            })
            .collect(),
        Err(e) => {
            tracing::warn!("compute_highlights: lindera tokenize failed: {}", e);
            Vec::new()
        }
    }
}

#[cfg(not(feature = "lindera"))]
fn lindera_tokens(_text: &str, _kind: FtsTokenizerKind) -> Vec<TokenSpan<'static>> {
    // Reaching this code is a build-time bug: `FtsTokenizerKind::requires_lindera`
    // already aborts process startup when the env requests a lindera kind
    // without the feature. Returning an empty vec keeps the call site
    // total (no panic in release) while the spec-mandated startup check
    // is the real safety net.
    Vec::new()
}

/// Process-wide Lindera tokenizer cache.
///
/// The dictionary is the expensive resource (~30 MB for IPADIC); the
/// `Tokenizer` itself is cheap once the dictionary is loaded. Each
/// kind owns its own `OnceLock<CacheEntry>` so:
///   - the steady-state hot path is fully lock-free
///     (`OnceLock::get` returns a `&CacheEntry` without taking a
///     `Mutex`),
///   - an in-flight load on one kind never blocks searches against a
///     different kind,
///   - a load failure is captured as `None` inside the `CacheEntry`,
///     so subsequent searches return empty highlights immediately
///     instead of retrying — and re-logging — the failed load.
#[cfg(feature = "lindera")]
mod lindera_cache {
    use std::path::PathBuf;
    use std::sync::{Arc, OnceLock};

    use lindera::dictionary::load_dictionary_from_path;
    use lindera::mode::Mode;
    use lindera::segmenter::Segmenter;
    use lindera::tokenizer::Tokenizer;

    use super::FtsTokenizerKind;

    type CacheEntry = Option<Arc<Tokenizer>>;

    static IPADIC: OnceLock<CacheEntry> = OnceLock::new();
    static UNIDIC: OnceLock<CacheEntry> = OnceLock::new();
    static KO_DIC: OnceLock<CacheEntry> = OnceLock::new();

    pub(super) fn get_or_init(kind: FtsTokenizerKind) -> Option<Arc<Tokenizer>> {
        let slot = match kind {
            FtsTokenizerKind::LinderaIpadic => &IPADIC,
            FtsTokenizerKind::LinderaUnidic => &UNIDIC,
            FtsTokenizerKind::LinderaKoDic => &KO_DIC,
            _ => return None,
        };
        // `OnceLock::get_or_init` serializes only racing initializers
        // for the same `OnceLock`; a different kind's slot is
        // independently stored, so its load progresses in parallel.
        slot.get_or_init(|| build(kind)).clone()
    }

    fn build(kind: FtsTokenizerKind) -> CacheEntry {
        let dict_path = dict_path_for(kind)?;
        match load_dictionary_from_path(&dict_path) {
            Ok(dictionary) => {
                let segmenter = Segmenter::new(Mode::Normal, dictionary, None);
                Some(Arc::new(Tokenizer::new(segmenter)))
            }
            Err(e) => {
                tracing::warn!(
                    "compute_highlights: failed to load Lindera dictionary at {:?}: {}; \
                     highlights for this kind will be skipped",
                    dict_path,
                    e
                );
                None
            }
        }
    }

    /// Mirrors lance-index's `LinderaBuilder::load`:
    /// `$LANCE_LANGUAGE_MODEL_HOME/lindera/<dict>/`. The default
    /// chosen here matches `docs/lindera-testing.md` so a developer
    /// who follows the docs sees Lindera highlights work without
    /// extra env tweaks.
    fn dict_path_for(kind: FtsTokenizerKind) -> Option<PathBuf> {
        let model_home = std::env::var("LANCE_LANGUAGE_MODEL_HOME").unwrap_or_else(|_| {
            std::env::var("HOME")
                .map(|h| format!("{h}/lance/language_models"))
                .unwrap_or_else(|_| "/var/lib/lance/language_models".to_string())
        });
        let dict_subdir = match kind {
            FtsTokenizerKind::LinderaIpadic => "ipadic",
            FtsTokenizerKind::LinderaUnidic => "unidic",
            FtsTokenizerKind::LinderaKoDic => "ko-dic",
            _ => return None,
        };
        Some(PathBuf::from(model_home).join("lindera").join(dict_subdir))
    }
}

/// Apply the Snowball English Porter stemmer to a token. Mirrors
/// `tantivy::tokenizer::Stemmer::new(Language::English)` which is what
/// lance-index 4.0.0 wires into `InvertedIndexParams::build` when
/// `stem = true` and `language = English` (`tokenizer.rs:348-349`).
/// tantivy's stemmer is itself a thin wrapper around `rust_stemmers`,
/// so going through `rust_stemmers` directly produces the same output
/// without forcing tantivy as a direct dependency.
///
/// Other languages (French, German, ...) are out of scope for this
/// pass — see `docs/vectordb-open-issues.md` L11 for the structural
/// fix that adds a `language` field to `FtsConfig` so this branch
/// can dispatch on it. Until then we lock to English to match the
/// `simple` / `whitespace` preset (the only presets where `stem` is
/// true) and lance-index's `InvertedIndexParams::new` default
/// (`tokenizer.rs:198-211` — `Language::English`).
fn apply_english_stem(s: &str) -> String {
    static STEMMER: OnceLock<Stemmer> = OnceLock::new();
    let stemmer = STEMMER.get_or_init(|| Stemmer::create(Algorithm::English));
    stemmer.stem(s).into_owned()
}

/// English stop word predicate. The list is the 33-word Lucene
/// `EnglishAnalyzer` set (Apache-2.0), which is the same list tantivy
/// 0.24's `StopWordFilter::new(Language::English)` returns from its
/// private `&[&str]` literal (`stop_word_filter/mod.rs:44-48`). tantivy
/// does not expose this list as a public constant, so reproducing it
/// here is the only way to keep the highlight side in sync without
/// pulling tantivy as a direct dependency. If lance-index ever changes
/// its English stop-word source, this constant must be re-synced — the
/// `docs/vectordb-open-issues.md` L11 entry tracks the structural fix.
const ENGLISH_STOP_WORDS: &[&str] = &[
    "a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "into", "is", "it",
    "no", "not", "of", "on", "or", "such", "that", "the", "their", "then", "there", "these",
    "they", "this", "to", "was", "will", "with",
];

fn is_english_stop_word(s: &str) -> bool {
    ENGLISH_STOP_WORDS.binary_search(&s).is_ok()
}

/// Strip simple ASCII diacritics so a query "naive" matches "naïve".
/// This deliberately covers only the Latin-1 supplement / Latin
/// Extended blocks that LanceDB's `ascii_folding` builder also
/// normalises; non-Latin scripts (CJK, Cyrillic) pass through
/// unchanged.
fn ascii_fold(s: &str) -> String {
    s.chars().map(fold_char).collect()
}

fn fold_char(c: char) -> char {
    match c {
        'À'..='Å' => 'A',
        'à'..='å' => 'a',
        'Ç' => 'C',
        'ç' => 'c',
        'È'..='Ë' => 'E',
        'è'..='ë' => 'e',
        'Ì'..='Ï' => 'I',
        'ì'..='ï' => 'i',
        'Ñ' => 'N',
        'ñ' => 'n',
        'Ò'..='Ö' | 'Ø' => 'O',
        'ò'..='ö' | 'ø' => 'o',
        'Ù'..='Ü' => 'U',
        'ù'..='ü' => 'u',
        'Ý' | 'Ÿ' => 'Y',
        'ý' | 'ÿ' => 'y',
        other => other,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::infra::memory_vector::config::FtsConfig;

    fn ngram_cfg() -> FtsConfig {
        FtsConfig::apply_preset(FtsTokenizerKind::Ngram)
    }

    fn ngram_prefix_only_cfg() -> FtsConfig {
        let mut cfg = FtsConfig::apply_preset(FtsTokenizerKind::Ngram);
        cfg.ngram_prefix_only = true;
        cfg
    }

    fn simple_cfg() -> FtsConfig {
        FtsConfig::apply_preset(FtsTokenizerKind::Simple)
    }

    /// ASCII query, single occurrence — sanity check that the utf16
    /// offsets mirror the byte offsets for pure ASCII content.
    #[test]
    fn test_highlight_ascii_simple_offsets() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("hello world", "hello", &cfg);
        assert_eq!(ranges.len(), 1);
        let r = &ranges[0];
        assert_eq!(r.byte_start, 0);
        assert_eq!(r.byte_length, 5);
        assert_eq!(r.utf16_start, 0);
        assert_eq!(r.utf16_length, 5);
    }

    /// Same word multiple times — each occurrence's `utf16_start` must be
    /// independent. This locks in the regression that motivated returning
    /// offsets from the server (a client-side `String.indexOf()` always
    /// returns the first match position).
    #[test]
    fn test_highlight_repeated_term_independent_offsets() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("foo bar foo bar foo", "foo", &cfg);
        assert_eq!(ranges.len(), 3);
        let utf16_starts: Vec<u32> = ranges.iter().map(|r| r.utf16_start).collect();
        assert_eq!(utf16_starts, vec![0, 8, 16]);
        for r in &ranges {
            assert_eq!(r.byte_length, 3);
            assert_eq!(r.utf16_length, 3);
        }
    }

    /// Surrogate-pair emoji highlighted via 2-gram windowing covers
    /// two characters (1 emoji + adjacent char). Boundary asserts
    /// must hold and `utf16_length` must agree with
    /// `slice.encode_utf16().count()` so the emoji is treated as a
    /// single unit (no mid-codepoint split).
    #[test]
    fn test_highlight_surrogate_pair_emoji_char_boundaries() {
        let cfg = ngram_cfg();
        let text = "ab🌍cd";
        let ranges = compute_highlights(text, "b🌍", &cfg);
        assert!(
            !ranges.is_empty(),
            "expected at least one range for query containing surrogate pair"
        );
        for r in &ranges {
            let bs = r.byte_start as usize;
            let be = bs + r.byte_length as usize;
            assert!(
                text.is_char_boundary(bs) && text.is_char_boundary(be),
                "bytes {}..{} must be on char boundaries in {:?}",
                bs,
                be,
                text
            );
            let slice = &text[bs..be];
            assert_eq!(r.utf16_length as usize, slice.encode_utf16().count());
        }
        let containing_emoji = ranges
            .iter()
            .find(|r| {
                let bs = r.byte_start as usize;
                let be = bs + r.byte_length as usize;
                text[bs..be].contains('🌍')
            })
            .expect("a range covering the emoji is required");
        assert!(containing_emoji.utf16_length >= 2);
    }

    /// ZWJ sequence as a single UTF-8 / UTF-16 unit: 25 bytes / 11
    /// utf16 code units (4 emoji × 4 bytes + 3 ZWJs × 3 bytes = 25).
    /// Whether ngram captures the whole sequence depends on
    /// `ngram_max`, so we assert boundary properties on every
    /// returned range rather than the exact length.
    #[test]
    fn test_highlight_zwj_sequence_offsets_are_char_boundaries() {
        let cfg = ngram_cfg();
        let text = "family 👨‍👩‍👧‍👦 here";
        let zwj = "👨‍👩‍👧‍👦";
        let ranges = compute_highlights(text, zwj, &cfg);
        for r in &ranges {
            let bs = r.byte_start as usize;
            let be = bs + r.byte_length as usize;
            assert!(
                text.is_char_boundary(bs),
                "byte_start {} not on a char boundary in {:?}",
                bs,
                text
            );
            assert!(
                text.is_char_boundary(be),
                "byte_end {} not on a char boundary in {:?}",
                be,
                text
            );
            let slice = &text[bs..be];
            assert_eq!(r.utf16_length as usize, slice.encode_utf16().count());
        }
    }

    /// Empty inputs short-circuit so we never call into the
    /// tokenizer with a degenerate value.
    #[test]
    fn test_highlight_empty_text_or_query_returns_empty() {
        let cfg = simple_cfg();
        assert!(compute_highlights("", "foo", &cfg).is_empty());
        assert!(compute_highlights("hello", "", &cfg).is_empty());
        assert!(compute_highlights("", "", &cfg).is_empty());
    }

    /// `lower_case = true` (set by the simple preset) must let an
    /// upper-case query match a lower-case content occurrence.
    #[test]
    fn test_highlight_lower_case_normalization() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("Hello World", "hello", &cfg);
        assert_eq!(ranges.len(), 1);
        assert_eq!(ranges[0].byte_start, 0);
        assert_eq!(ranges[0].byte_length, 5);
    }

    /// `ascii_folding = true` must make `naive` match `naïve`. The
    /// content keeps its original byte length (4 + 'ï' is 2 bytes =
    /// 5), proving that the byte / utf16 lengths reflect the
    /// *source* text, not the folded form.
    #[test]
    fn test_highlight_ascii_folding() {
        let cfg = simple_cfg();
        let text = "naïve";
        let ranges = compute_highlights(text, "naive", &cfg);
        assert_eq!(ranges.len(), 1);
        let r = &ranges[0];
        assert_eq!(r.byte_start, 0);
        assert_eq!(r.byte_length as usize, text.len());
        assert_eq!(r.utf16_length, 5);
    }

    /// Ngram tokenizer must NOT leak its 2/3-char window fragments to
    /// the client: query="rust" / text="rust" should yield a single
    /// merged range covering the whole word, not five overlapping
    /// `ru`/`us`/`st`/`rus`/`ust` fragments. Locks in the regression
    /// that motivated server-side range merging.
    #[test]
    fn test_highlight_ngram_merges_overlapping_fragments() {
        let cfg = ngram_cfg();
        let ranges = compute_highlights("rust", "rust", &cfg);
        assert_eq!(
            ranges.len(),
            1,
            "expected a single merged range, got {ranges:?}"
        );
        let r = &ranges[0];
        assert_eq!(r.byte_start, 0);
        assert_eq!(r.byte_length, 4);
        assert_eq!(r.utf16_start, 0);
        assert_eq!(r.utf16_length, 4);
    }

    /// Partial match: query="rust" / text="rustacean" — only the
    /// `rust` prefix is covered by overlapping ngram fragments and
    /// must collapse to a single 0..4 range. The trailing `acean`
    /// must not appear in the output.
    #[test]
    fn test_highlight_ngram_partial_match_merges_to_prefix() {
        let cfg = ngram_cfg();
        let ranges = compute_highlights("rustacean", "rust", &cfg);
        assert_eq!(ranges.len(), 1, "expected 1 merged range, got {ranges:?}");
        let r = &ranges[0];
        assert_eq!(r.byte_start, 0);
        assert_eq!(r.byte_length, 4);
    }

    /// Output ranges must be sorted by `byte_start` and pairwise
    /// non-overlapping. Tested across two tokenizers so the post-
    /// processing contract holds regardless of token source.
    #[test]
    fn test_highlight_ranges_are_sorted_and_disjoint() {
        for cfg in [ngram_cfg(), simple_cfg()] {
            let ranges = compute_highlights("foo bar foo bar foo", "foo", &cfg);
            for win in ranges.windows(2) {
                let a = &win[0];
                let b = &win[1];
                let a_end = a.byte_start + a.byte_length;
                assert!(
                    a_end <= b.byte_start,
                    "ranges must be disjoint: {a:?} then {b:?}"
                );
                assert!(
                    a.byte_start < b.byte_start,
                    "ranges must be strictly increasing: {a:?} then {b:?}"
                );
            }
        }
    }

    /// Merging must preserve UTF-8 char boundaries — the merged
    /// `byte_start..byte_end` is still a valid `&str` slice and
    /// `utf16_length` agrees with the actual UTF-16 encoding of that
    /// slice. Catches a bug where naive merge could splice across a
    /// multi-byte codepoint.
    #[test]
    fn test_highlight_ngram_merge_keeps_char_boundaries_emoji() {
        let cfg = ngram_cfg();
        let text = "ab🌍cd";
        let ranges = compute_highlights(text, "b🌍c", &cfg);
        assert!(!ranges.is_empty());
        for r in &ranges {
            let bs = r.byte_start as usize;
            let be = bs + r.byte_length as usize;
            assert!(text.is_char_boundary(bs));
            assert!(text.is_char_boundary(be));
            let slice = &text[bs..be];
            assert_eq!(r.utf16_length as usize, slice.encode_utf16().count());
        }
    }

    /// `simple` preset enables English stemming (Porter via
    /// rust-stemmers, the same family lance-index/tantivy uses for
    /// Language::English). A query like "running" must therefore
    /// highlight occurrences of "runs" / "run" in the text — both
    /// stem to the same form. Without this, BM25 hits computed on
    /// stemmed tokens would still produce empty highlight ranges,
    /// which is exactly the FTS↔highlight drift the P2 review flagged.
    #[test]
    fn test_highlight_simple_stem_running_matches_runs() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("she runs daily", "running", &cfg);
        assert_eq!(
            ranges.len(),
            1,
            "expected exactly one stemmed match, got {ranges:?}"
        );
        let r = &ranges[0];
        let bs = r.byte_start as usize;
        let be = bs + r.byte_length as usize;
        assert_eq!(&"she runs daily"[bs..be], "runs");
    }

    /// Reverse direction: stemming must work both for query and text,
    /// so a query="run" against text="running" must also hit. This
    /// catches a regression where stem is applied to one side only.
    #[test]
    fn test_highlight_simple_stem_run_matches_running() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("running fast", "run", &cfg);
        assert_eq!(ranges.len(), 1, "got {ranges:?}");
        let r = &ranges[0];
        let bs = r.byte_start as usize;
        let be = bs + r.byte_length as usize;
        assert_eq!(&"running fast"[bs..be], "running");
    }

    /// `simple` preset also enables `remove_stop_words = true`. A
    /// mixed query "the rust" must not produce a highlight on "the"
    /// (it would visually pollute every English sentence) — only the
    /// content-bearing token "rust" survives the stop-word filter on
    /// the query side. The text-side filter is symmetric, so common
    /// stop words inside the content are not eligible matches even
    /// when the query is itself a stop word.
    #[test]
    fn test_highlight_simple_stop_words_filtered_from_query() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("the rust language", "the rust", &cfg);
        for r in &ranges {
            let bs = r.byte_start as usize;
            let be = bs + r.byte_length as usize;
            let slice = &"the rust language"[bs..be];
            assert_ne!(
                slice.to_lowercase(),
                "the",
                "stop word 'the' must not be highlighted"
            );
        }
        assert!(
            ranges.iter().any(|r| {
                let bs = r.byte_start as usize;
                let be = bs + r.byte_length as usize;
                &"the rust language"[bs..be] == "rust"
            }),
            "'rust' should still be highlighted"
        );
    }

    /// Pure stop-word query should produce zero highlights. Without
    /// this the highlight pass would happily light up every "the" in
    /// a search result whose BM25 score came from other terms.
    #[test]
    fn test_highlight_simple_stop_word_only_query_is_empty() {
        let cfg = simple_cfg();
        let ranges = compute_highlights("the quick brown fox", "the", &cfg);
        assert!(
            ranges.is_empty(),
            "stop-word-only query must produce no highlights, got {ranges:?}"
        );
    }

    /// `simple` preset caps `max_token_length` at 40 (matching
    /// the FtsIndexBuilder default for the simple preset). Tokens
    /// longer than the cap are dropped on the index side, so the
    /// highlight side must drop them too — otherwise the highlight
    /// would mark text the BM25 index never indexed.
    #[test]
    fn test_highlight_simple_max_token_length_drops_long_tokens() {
        let cfg = simple_cfg();
        // 50-byte (ASCII) token, well over the 40-byte cap.
        let long = "a".repeat(50);
        let text = format!("prefix {long} suffix");
        let ranges = compute_highlights(&text, &long, &cfg);
        assert!(
            ranges.is_empty(),
            "tokens longer than max_token_length must not be highlighted, got {ranges:?}"
        );
    }

    /// tantivy's `RemoveLongFilter` keeps `token.text.len() < limit`
    /// — i.e. the comparison is **strictly** less-than on **UTF-8
    /// byte length**. So with `max_token_length = 40`:
    ///   - 39-byte token → kept
    ///   - 40-byte token → dropped (`40 < 40` is false)
    ///   - 41-byte token → dropped
    ///
    /// Any deviation here puts BM25 hits and highlight ranges out of
    /// sync at the boundary. This regression test pins all three
    /// boundary cases at once because the boundary is the one place
    /// off-by-one bugs love to hide.
    #[test]
    fn test_highlight_simple_max_token_length_byte_boundary() {
        let cfg = simple_cfg();
        let limit = cfg.max_token_length.expect("simple preset has limit");
        assert_eq!(limit, 40);

        // 39 ASCII bytes — kept.
        let kept = "a".repeat(39);
        let text_kept = format!("prefix {kept} suffix");
        let ranges = compute_highlights(&text_kept, &kept, &cfg);
        assert!(
            !ranges.is_empty(),
            "39-byte token must be highlighted (limit-1), got {ranges:?}"
        );

        // 40 ASCII bytes — dropped (strict less-than on the index side).
        let at_limit = "b".repeat(40);
        let text_at = format!("prefix {at_limit} suffix");
        let ranges = compute_highlights(&text_at, &at_limit, &cfg);
        assert!(
            ranges.is_empty(),
            "40-byte token must be dropped (== limit, tantivy uses '<'), got {ranges:?}"
        );

        // 41 ASCII bytes — dropped.
        let over = "c".repeat(41);
        let text_over = format!("prefix {over} suffix");
        let ranges = compute_highlights(&text_over, &over, &cfg);
        assert!(
            ranges.is_empty(),
            "41-byte token must be dropped, got {ranges:?}"
        );
    }

    /// Unit must be **bytes**, not chars. A 14-character Japanese
    /// token that is 42 UTF-8 bytes (each kanji = 3 bytes) must be
    /// dropped at `max_token_length = 40`, even though its char count
    /// is well under 40. The earlier implementation used char count,
    /// which would have kept this token and produced highlights for
    /// content the BM25 index dropped. This test pins the byte-length
    /// semantics. (Lindera/ngram presets disable max_token_length, so
    /// we synthesize a config with the simple preset's filter chain
    /// while keeping the simple tokenizer — which splits on
    /// non-alphanumeric — to avoid pulling in a Japanese tokenizer.
    /// We sidestep tokenization by using ASCII Latin-1 punctuation as
    /// a delimiter, but for the byte-vs-char distinction we still
    /// need a multi-byte body.)
    #[test]
    fn test_highlight_simple_max_token_length_counts_bytes_not_chars() {
        let cfg = simple_cfg();
        // 14 kanji × 3 bytes = 42 bytes. char_count = 14 (well under 40).
        // Surface from `simple_tokens` (which keeps alphanumeric runs)
        // would split on non-alphanumeric, but kanji ARE alphanumeric
        // per Unicode, so the whole sequence becomes one token.
        let long_jp = "日本語処理試験用長文字列単体token"; // 16 chars approx
        // Verify our setup: char count < limit, byte length > limit
        assert!(long_jp.chars().count() < 40, "should be < 40 chars");
        assert!(long_jp.len() >= 40, "should be >= 40 bytes");

        let text = format!("前置 {long_jp} 後置");
        let ranges = compute_highlights(&text, long_jp, &cfg);
        assert!(
            ranges.is_empty(),
            "multi-byte token whose byte length >= limit must be dropped, got {ranges:?}"
        );
    }

    /// `ngram_prefix_only=true` mirrors tantivy's
    /// `NgramTokenStream::advance` which terminates the stream as
    /// soon as `offset_from > 0` is reached
    /// (`tantivy/src/tokenizer/ngram_tokenizer.rs:163-177`). In other
    /// words, only n-grams that start at byte 0 are emitted. The FTS
    /// index built with `MEMORY_FTS_NGRAM_PREFIX_ONLY=true` therefore
    /// only matches by leading-edge prefix, and the highlight side
    /// must shrink to the same set — otherwise a BM25 hit on a
    /// prefix-only query would highlight unrelated mid-text n-grams
    /// the index never indexed.
    ///
    /// `text="abxyz" / query="xy"` — `"xy"` starts at byte 2 in the
    /// text. With the default `prefix_only=false` it is highlighted
    /// (any-position 2-gram match). With `prefix_only=true` no
    /// highlight should be produced because neither side has an
    /// n-gram starting at byte 0 that matches the other side's prefix
    /// n-grams.
    #[test]
    fn test_highlight_ngram_prefix_only_drops_mid_string_match() {
        let default_cfg = ngram_cfg();
        let prefix_cfg = ngram_prefix_only_cfg();

        let ranges_default = compute_highlights("abxyz", "xy", &default_cfg);
        assert!(
            !ranges_default.is_empty(),
            "default ngram (prefix_only=false) must still match mid-string ngram, \
             baseline got {ranges_default:?}"
        );

        let ranges_prefix = compute_highlights("abxyz", "xy", &prefix_cfg);
        assert!(
            ranges_prefix.is_empty(),
            "prefix_only=true must not highlight mid-string ngrams, got {ranges_prefix:?}"
        );
    }

    /// Companion to the previous test: when the match IS at byte 0,
    /// `prefix_only=true` must still produce a highlight. This guards
    /// against an over-correction that throws away every ngram match.
    #[test]
    fn test_highlight_ngram_prefix_only_keeps_leading_edge_match() {
        let prefix_cfg = ngram_prefix_only_cfg();
        let ranges = compute_highlights("rust language", "ru", &prefix_cfg);
        assert!(
            !ranges.is_empty(),
            "prefix_only=true must still highlight a leading-edge ngram, got {ranges:?}"
        );
        // The first range must start at byte 0 — that is the whole
        // point of prefix-only mode. (Other prefix-position ngrams
        // like "rus" merge into the same span via `merge_ranges`.)
        assert_eq!(
            ranges[0].byte_start, 0,
            "leading-edge match must start at byte 0, got {ranges:?}"
        );
    }

    /// `prefix_only` discrimination must apply symmetrically to query
    /// and text — both sides re-tokenize through `tokenize_for_match`,
    /// so a match needs the *same byte-0-anchored* set on both sides.
    /// Crafted case: `text="run" / query="hellorun"`. Without
    /// prefix_only, both sides produce 2-/3-grams "ru"/"un"/"run" so
    /// "run" is highlighted. With prefix_only, the query side only
    /// produces "he"/"hel" (its leading edge), the text side only
    /// produces "ru"/"run", and the two sets are disjoint — no
    /// highlight.
    #[test]
    fn test_highlight_ngram_prefix_only_symmetric_on_query_and_text() {
        let default_cfg = ngram_cfg();
        let prefix_cfg = ngram_prefix_only_cfg();

        let ranges_default = compute_highlights("run", "hellorun", &default_cfg);
        assert!(
            !ranges_default.is_empty(),
            "default ngram baseline must match: {ranges_default:?}"
        );

        let ranges_prefix = compute_highlights("run", "hellorun", &prefix_cfg);
        assert!(
            ranges_prefix.is_empty(),
            "prefix_only=true must drop matches that don't share a leading-edge ngram \
             on both sides, got {ranges_prefix:?}"
        );
    }

    /// Counter-test: ngram preset has `stem = false` and
    /// `remove_stop_words = false`, so the English stemmer must NOT
    /// be invoked on the ngram path. With ngram, "running" / "run"
    /// share no 3-gram (the closest is "run" vs "run" inside
    /// "running" — which actually DOES match by character window).
    /// To pin "no English stemming on ngram", we use a pair where
    /// stemming would create a match but ngram alone cannot:
    /// query="happiness" / text="happy" — no shared 3-gram window
    /// (`hap` matches; `app` differs from text's `app` only because
    /// text has it; here intentionally pick a pair with no overlap).
    /// Concretely, with ngram preset (`min=2, max=3`), if stemming
    /// were leaking in we'd get a hit for query="ponies" /
    /// text="poni" (Porter stem `ponies → poni`) — but we expect
    /// zero hits because ngram does not stem.
    #[test]
    fn test_highlight_ngram_does_not_stem() {
        let cfg = ngram_cfg();
        // With Porter stem: ponies → poni, so a stem-aware path would
        // find "poni" in text. Ngram preset must NOT do this.
        // Instead, ngram will match the 2-gram "po" / "on" / "ni" —
        // those exist literally in both, so we cannot use that pair
        // to disprove stemming. We pick a pair where the surface
        // ngrams of query are absent from text: query="zzzunique" /
        // text="zzzuniq". Stemmer would NOT make these match either,
        // so this is just a sanity check; the real assertion is that
        // ngram preset's `stem` field is false (locked in
        // config.rs::preset_ngram_disables_stemming_and_stop_words).
        // Here we only assert the preset value at runtime so a future
        // accidental flip is caught by the highlight test suite too.
        assert!(!cfg.stem, "ngram preset must not enable stem");
        assert!(
            !cfg.remove_stop_words,
            "ngram preset must not enable stop-words"
        );
    }

    /// With the lindera/ipadic tokenizer the compound query
    /// "言語処理" must split at the morpheme boundary and highlight
    /// the constituent terms ("言語", "処理") in
    /// "自然言語処理は楽しい". Gated to
    /// `--features lindera --ignored` so CI without IPADIC
    /// dictionaries simply skips this case.
    #[cfg(feature = "lindera")]
    #[test]
    #[ignore = "requires LANCE_LANGUAGE_MODEL_HOME with lindera/ipadic dictionary"]
    fn test_highlight_japanese_lindera_compound_split() {
        let cfg = FtsConfig::apply_preset(FtsTokenizerKind::LinderaIpadic);
        let text = "自然言語処理は楽しい";
        let ranges = compute_highlights(text, "言語処理", &cfg);
        assert!(
            !ranges.is_empty(),
            "lindera must surface at least one of the constituent morphemes"
        );
        for r in &ranges {
            let bs = r.byte_start as usize;
            let be = bs + r.byte_length as usize;
            assert!(text.is_char_boundary(bs));
            assert!(text.is_char_boundary(be));
            let slice = &text[bs..be];
            assert_eq!(r.utf16_length as usize, slice.encode_utf16().count());
        }
    }
}
